"""initial

Revision ID: afff8821f433
Revises: 
Create Date: 2026-09-18 21:48:55.658821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afff8821f433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_uid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('entity_summary', sa.JSON(), nullable=False),
    sa.Column('disposition_note', sa.String(), nullable=False),
    sa.Column('reported_at_alerts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_uid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('innate', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('suppressed', sa.Integer(), nullable=False),
    sa.Column('why', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_asset_type_created', 'alerts', ['asset', 'type', 'created_at'], unique=False)
    op.create_index('idx_alerts_case_id', 'alerts', ['case_id'], unique=False)
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_source', 'alerts', ['source'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('iocs_json', sa.JSON(), nullable=False),
    sa.Column('unknowns_json', sa.JSON(), nullable=False),
    sa.Column('remediations_json', sa.JSON(), nullable=False),
    sa.Column('attack_chain_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('alert_artifacts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'artifact_id')
    )
    op.create_index('idx_alert_artifacts_alert_id', 'alert_artifacts', ['alert_id'], unique=False)
    op.create_index('idx_alert_artifacts_artifact_id', 'alert_artifacts', ['artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alert_artifacts_artifact_id', table_name='alert_artifacts')
    op.drop_index('idx_alert_artifacts_alert_id', table_name='alert_artifacts')
    op.drop_table('alert_artifacts')
    op.drop_table('reports')
    op.drop_index('idx_alerts_source', table_name='alerts')
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_index('idx_alerts_case_id', table_name='alerts')
    op.drop_index('idx_alerts_asset_type_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('cases')
    op.drop_table('audit_logs')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
