"""add assets table

Revision ID: b86e32e1cf77
Revises: afff8821f433
Create Date: 2026-09-19 21:50:52.847405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86e32e1cf77'
down_revision = 'afff8821f433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_role', 'assets', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assets_role', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
